// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abkfaimjsuqojnkcffot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFia2ZhaW1qc3Vxb2pua2NmZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NjM1MTMsImV4cCI6MjA5MDQzOTUxM30.eMD4600DnVvJJsNblC_7kIletGq8E7YzVIs6zMV5BZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});